### ISSUE TITLE
add SisuConfig class

### ISSUE THREAD

**Issue by tmshv** [designunit/sisu#36]
- add `SisuConfig` class in `sisulib`
- move or copy `get_related_layers` to `get_layers` method of this class (take care of dependents of `get_related_layers`)
- add a function `sisuconfig` to `rhinolib` which work same as `get_sisufile` but returns instance of `SisuConfig`
- modify `SisuHide`/`SisuShow` and `SisuLock`/`SisuUnlock` commands to work with this setup

**Comment by modernpacifist** [comment]
Thank you

**Comment by tmshv** [comment]
also would be nice if you can some tests to this class

**Comment by modernpacifist** [comment]
Ok, no problem

**Comment by modernpacifist** [comment]
Sisuconfig class was implemented in pull request #37
